version: '3'

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: SpringBootMySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testspringboot
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/docker/SpringBoot/db/data:/var/lib/mysql
      - ~/docker/SpringBoot/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ~/docker/SpringBoot/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306
