logging:
  level:
    root: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/springboot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 18080
