logging:
  level:
#    root: DEBUG
    com.example.dmb: DEBUG
    web: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/springboot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 15000
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 8
      minimum-idle: 10
      idle-timeout: 100000
      leak-detection-threshold: 5000
      read-only: false
      auto-commit: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 6MB
  security:
    user:
      name: user
      password: pass

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    docExpansion: none # ["list"*, "full", "none"]

server:
  port: 8080
