# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Check Style
      run: |
        export SPRING_PROFILES_ACTIVE=test
        ./gradlew clean
        ./gradlew checkstyleMain

    - name: Docker Compose Run
      run: |
        docker-compose up -d
        while ! docker-compose exec -T db mysql -e "SELECT 1" >/dev/null 2>&1
        do
          sleep 1
        done

    - name: DB Migrate
      run: |
        export SPRING_PROFILES_ACTIVE=test
        ./gradlew flywayClean
        ./gradlew flywayMigrate

    - name: Test
      run: |
        export SPRING_PROFILES_ACTIVE=test
        ./gradlew clean
        ./gradlew test
        
    - name: Upload Test Result
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: build/reports/**/*
